apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki.micros.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.micros.svc.cluster.local:9411"
  PRODUCT_SERVICE_URL: "http://product-service.micros.svc.cluster.local:8080"
  ORDER_SERVICE_URL: "http://order-service.micros.svc.cluster.local:8081"
  INVENTORY_SERVICE_URL: "http://inventory-service.micros.svc.cluster.local:8082"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.micros.svc.cluster.local:29092"